baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Italicmew'
theme = 'hugo-paper'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10